name: Flutter Nightly Build

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      windows:
        description: "Windows"
        type: boolean
        default: true
      android:
        description: "Android"
        type: boolean
        default: true
      linux:
        description: "Linux"
        type: boolean
        default: false
      macos:
        description: "macOS"
        type: boolean
        default: false
      ios:
        description: "iOS"
        type: boolean
        default: false

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
      windows: ${{ inputs.windows }}
      android: ${{ inputs.android }}
      linux: ${{ inputs.linux }}
      macos: ${{ inputs.macos }}
      ios: ${{ inputs.ios }}
